name: fend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alert_dialog: ^1.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dropdown_search: ^0.5.0
  email_validator: ^2.0.1
  fl_chart: ^0.35.0
  flutter_email_sender: ^5.0.0
  http: ^0.13.1
  http_parser: ^4.0.0
  image_picker: ^0.7.4
  mailer: ^5.0.0
  mailer2: ^1.2.5
  path: ^1.8.0
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  syncfusion_flutter_calendar: ^19.1.58
  weekday_selector: ^1.0.0
  flutter_downloader: ^1.6.0
  permission_handler: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/001-woman.png
    - assets/002-man.png
    - assets/003-woman.png
    - assets/004-woman.png
    - assets/005-man.png
    - assets/006-woman.png
    - assets/007-woman.png
    - assets/008-woman.png
    - assets/009-woman.png
    - assets/010-woman.png
    - assets/011-man.png
    - assets/012-woman.png
    - assets/013-man.png
    - assets/014-man.png
    - assets/015-woman.png
    - assets/016-woman.png
    - assets/017-woman.png
    - assets/018-woman.png
    - assets/019-man.png
    - assets/020-man.png
    - assets/021-man.png
    - assets/022-woman.png
    - assets/023-woman.png
    - assets/024-man.png
    - assets/025-woman.png
    - assets/026-man.png
    - assets/027-woman.png
    - assets/028-woman.png
    - assets/029-man.png
    - assets/030-woman.png
    - assets/031-woman.png
    - assets/032-man.png
    - assets/033-woman.png
    - assets/034-man.png
    - assets/035-woman.png
    - assets/036-man.png
    - assets/037-woman.png
    - assets/038-man.png
    - assets/039-woman.png
    - assets/040-woman.png
    - assets/041-man.png
    - assets/042-woman.png
    - assets/043-woman.png
    - assets/044-woman.png
    - assets/045-woman.png
    - assets/046-woman.png
    - assets/047-woman.png
    - assets/048-woman.png
    - assets/049-man.png
    - assets/050-woman.png
    - assets/instagram_logo.png
    - assets/study_material_folder.png
    - assets/study_material_file.png
    - assets/bg1.png
    - assets/bg2.png